#!/bin/bash
sed -i -- "s|__SERVICE_PHP_FPM_ADDRESS_IP__|$SERVICE_PHP_FPM_ADDRESS_IP|g" /etc/nginx/conf.d/default.conf
sed -i -- "s|__SERVICE_PHP_FPM_ADDRESS_PORT__|$SERVICE_PHP_FPM_ADDRESS_PORT|g" /etc/nginx/conf.d/default.conf

cat /etc/nginx/conf.d/default.conf

nginx -g "daemon off;"
